#!/bin/sh
mkdir /tmp
mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug
mount -t tmpfs none /tmp

insmod /magic.ko
mdev -s
echo "4" > /proc/sys/kernel/printk
cat /proc/kallsyms|grep "prepare_kernel_cred"
cat /proc/kallsyms|grep "commit_creds"
cat /proc/kallsyms|grep "sk_alloc"
cat /proc/kallsyms|grep "sock_init_data"
cat /proc/kallsyms|grep "\]"
cat /proc/kallsyms|grep "memcmp"
cat /proc/kallsyms|grep "copy_from_user"
cat /proc/sys/kernel/printk

# normal user
setsid /bin/cttyhack setuidgid 1000 /bin/sh

umount /proc
poweroff -d 0  -f
